version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.3-stretch
    steps:
    - checkout
    - run:
        name: Bundle Install
        command: bundle install
    - run:
        name: Run Tests
        command: bundle exec rspec
